trigger:
  paths:
    include:
    - result/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6c2c234f-2f00-4b22-92be-1862650aae59'
  imageRepository: 'votingapplication'
  containerRegistry: 'mooazazuredevopsci.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'azureagent'

stages:
- stage: Build
  displayName: Build the image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: 'buildAndPush'
        repository: '$(imageRepository)'
        dockerfile: '$(dockerfilePath)'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: '$(tag)'
- stage: Push
  displayName: Push Stage
  jobs:
  - job: Push
    displayName: Push the image
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: 'push'
        repository: '$(imageRepository)'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: '$(tag)'
